### ISSUE TITLE
Add an option to disable default maps

### ISSUE THREAD

**Issue by yutkat** [cometsong/CommentFrame.vim#2]
I don't like default mappings. Could you add an option to disable?

**Comment by cometsong** [comment]
This is possible, and I agree much simpler than un/remapping each one.
I'll look into it, as it requires a bit of refactoring of the code.

**Comment by cometsong** [comment]
Done.  Added a plugin option to skip mapping the default keys called `g:CommentFrame_SkipDefaultMappings`. Let that equal any value (just checks if it `exists`) and the default mappings are not done.

**Comment by yutkat** [comment]
It works. Thank you!
